import {motion} from 'motion/react'
import type {Template} from '../types'
import {EASE,Frame,Eyebrow,Title} from './common'
export function PhotoFamily({t}:{t:Template}){return <Frame t={t} variant="photo"><Eyebrow>DOCUMENTARY / EVIDENCE</Eyebrow><Title>{t.name}</Title><motion.div className="premium__photo" initial={{clipPath:'inset(0 100% 0 0)'}} animate={{clipPath:'inset(0 0% 0 0)'}} transition={{duration:.75,ease:EASE}}><div className="premium__photoGrid"/></motion.div><motion.div className="premium__caption" initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:.5,duration:.45}}>CAPTION / VERIFIED CONTEXT</motion.div></Frame>}
export function ComparisonFamily({t}:{t:Template}){return <Frame t={t} variant="compare"><Eyebrow>COMPARISON / TWO STATES</Eyebrow><Title>{t.name}</Title><div className="premium__compare"><motion.div initial={{x:-18,opacity:0}} animate={{x:0,opacity:1}} transition={{duration:.55,ease:EASE}}><b>ANTES</b><i/></motion.div><motion.div initial={{x:18,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:.08,duration:.55,ease:EASE}}><b>DESPUÉS</b><i/></motion.div></div><div className="premium__delta">Δ VERIFIED</div></Frame>}
export function SystemFamily({t}:{t:Template}){return <Frame t={t} variant="system"><Eyebrow>SYSTEM / CONNECTED STORY</Eyebrow><Title>{t.name}</Title><div className="premium__system"><motion.i initial={{scale:0}} animate={{scale:1}}/><motion.span initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:.15,duration:.55,ease:EASE}}/><motion.i initial={{scale:0}} animate={{scale:1}} transition={{delay:.35}}/><motion.span initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:.45,duration:.55,ease:EASE}}/><motion.i initial={{scale:0}} animate={{scale:1}} transition={{delay:.7}}/></div><div className="premium__steps"><span>CONTEXT</span><span>ACTION</span><span>RESULT</span></div></Frame>}
export function TimelineFamily({t}:{t:Template}){return <Frame t={t} variant="timeline"><Eyebrow>TIMELINE / MILESTONES</Eyebrow><Title>{t.name}</Title><motion.div className="familyTimeline__line" initial={{scaleY:0}} animate={{scaleY:1}} transition={{duration:.85,ease:EASE}}/>{[0,1,2].map(i=><motion.div className={`familyTimeline__node n${i+1}`} key={i} initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:.18+i*.2}}><b>0{i+1}</b><span>MILESTONE</span></motion.div>)}</Frame>}
export function ManifestoFamily({t}:{t:Template}){return <Frame t={t} variant="manifesto"><Eyebrow>KINETIC / STATEMENT</Eyebrow><motion.div className="familyManifesto__words"><motion.b initial={{x:-26,opacity:0}} animate={{x:0,opacity:1}}>PUBLIC</motion.b><motion.b initial={{x:28,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:.12}}>VALUE</motion.b><motion.b initial={{scale:.78,opacity:0}} animate={{scale:1,opacity:1}} transition={{delay:.24}}>IN MOTION</motion.b></motion.div><div className="familyManifesto__accent"/></Frame>}
export function LongformFamily({t}:{t:Template}){return <Frame t={t} variant="longform"><Eyebrow>LONGFORM / CONTINUOUS STORY</Eyebrow><Title>{t.name}</Title><div className="familyLong__rail"><motion.i initial={{scaleY:0}} animate={{scaleY:1}} transition={{duration:1.1,ease:EASE}}/></div><div className="familyLong__scenes">{['OPEN','DATA','ROUTE','CLOSE'].map((x,i)=><motion.span key={x} initial={{opacity:0,x:10}} animate={{opacity:1,x:0}} transition={{delay:.12+i*.14}}><b>0{i+1}</b>{x}</motion.span>)}</div></Frame>}
