import {AbsoluteFill,Sequence,interpolate,useCurrentFrame,useVideoConfig} from 'remotion'
import {PremiumMaterial} from '../components/PremiumMaterials'
import {PremiumTransition,type PremiumTransitionId} from '../components/PremiumTransitions'

const brand={surface:'#ffffff',surfaceAlt:'#f5f7f8',ink:'#1D1D1B',muted:'#68727a',primary:'#00AAED',secondary:'#B5F6FF',accent:'#89033A',line:'#dce5e8'}
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const}
const groups=[
  {label:'LUNES',items:['Benito Juárez','Palo Alto','Buenavista','Villa Flores']},
  {label:'MARTES Y VIERNES',items:['Mirador de la Cumbre I y II','Moctezuma','Paraíso','Jardines del Sol']},
  {label:'MIÉRCOLES',items:['Del Valle','San Isidro','Lo de Villa']},
  {label:'JUEVES',items:['Tierra y Libertad','Palo Alto','Buenavista','Villa Flores']},
  {label:'SÁBADO',items:['Tierra y Libertad','El Moralete','De los Trabajadores','Patios del Ferrocarril','La Albarrada']}
]
const timings={hook:120,territory:150,journey:360,nodes:270,value:240,close:210}
const Safe=({children}:{children:React.ReactNode})=><div style={{position:'absolute',inset:'180px 96px 320px 96px'}}>{children}</div>
const Header=({label='RUTAS PROGRAMADAS'}:{label?:string})=><div style={{display:'flex',alignItems:'center',gap:14,fontSize:18,fontWeight:900,letterSpacing:3,color:brand.accent}}><span style={{width:52,height:5,borderRadius:99,background:brand.accent}}/>{label}</div>
const Footer=()=> <div style={{position:'absolute',left:96,right:96,bottom:120,height:118,borderTop:`1px solid ${brand.line}`,display:'grid',gridTemplateColumns:'1fr auto',alignItems:'center',gap:24}}><span style={{fontSize:12,fontWeight:850,letterSpacing:1.8,color:brand.muted}}>IDENTIDAD FINAL DESDE AGUA BIENESTAR DESIGN SYSTEM</span><span style={{fontSize:13,fontWeight:850}}>QA PREMIUM · 45 S</span></div>

function EndTransition({id,duration}:{id:PremiumTransitionId;duration:number}){const f=useCurrentFrame();const p=interpolate(f,[duration-18,duration-1],[0,1],clamp);return f>=duration-18?<PremiumTransition id={id} progress={p} brand={brand}/>:null}

function Hook(){const f=useCurrentFrame(),{fps}=useVideoConfig();const y=interpolate(f,[0,.8*fps],[34,0],clamp),op=interpolate(f,[0,.55*fps],[0,1],clamp),rule=interpolate(f,[.25*fps,2.4*fps],[12,88],clamp);return <AbsoluteFill style={{background:brand.surface,color:brand.ink}}><PremiumMaterial id="MAT-LIQUID-GLASS" brand={brand}/><Safe><div style={{paddingTop:80,position:'relative',zIndex:3}}><Header/><h1 style={{fontSize:124,lineHeight:.82,letterSpacing:-7,maxWidth:820,margin:'42px 0 0',transform:`translateY(${y}px)`,opacity:op}}>Rutas<br/><span style={{color:brand.accent}}>semanales</span></h1><div style={{marginTop:54,width:`${rule}%`,height:6,background:brand.primary,borderRadius:99}}/><p style={{fontSize:29,lineHeight:1.25,maxWidth:650,color:brand.muted,marginTop:30}}>Agua Bienestar · recorrido continuo por días y destinos.</p></div><div style={{position:'absolute',right:10,bottom:120,width:250,height:250,borderRadius:'50%',border:`1px solid ${brand.line}`,display:'grid',placeItems:'center'}}><div style={{width:58,height:58,background:brand.primary,rotate:'45deg',borderRadius:'52% 48% 55% 45% / 60% 42% 58% 40%',boxShadow:`0 0 0 18px color-mix(in srgb, ${brand.secondary} 55%, transparent)`}}/></div></Safe><Footer/><EndTransition id="PTR-LIQUID-WIPE" duration={timings.hook}/></AbsoluteFill>}

function Territory(){const f=useCurrentFrame(),{fps}=useVideoConfig();const pr=interpolate(f,[.4*fps,4.2*fps],[0,1],clamp);return <AbsoluteFill style={{background:brand.surface,color:brand.ink}}><PremiumMaterial id="MAT-TERRITORY-MESH" brand={brand}/><Safe><div style={{paddingTop:50}}><Header label="SEMANA / TERRITORIO"/><h2 style={{fontSize:82,lineHeight:.9,letterSpacing:-4,margin:'28px 0 0',maxWidth:680}}>Cinco jornadas,<br/>una sola <span style={{color:brand.accent}}>historia.</span></h2></div><div style={{position:'absolute',left:0,right:0,top:390,bottom:120,transform:'rotateX(54deg) rotateZ(-10deg)',transformOrigin:'50% 64%',background:`repeating-linear-gradient(90deg,transparent 0 118px,${brand.line} 118px 120px),repeating-linear-gradient(0deg,transparent 0 100px,${brand.line} 100px 102px)`,opacity:.5}}/><svg viewBox="0 0 900 650" style={{position:'absolute',left:0,right:0,top:470,width:'100%',height:650,overflow:'visible'}}><path d="M90 530 L245 440 L405 345 L575 265 L790 130" fill="none" stroke={brand.line} strokeWidth="12" strokeLinecap="round"/><path d="M90 530 L245 440 L405 345 L575 265 L790 130" fill="none" stroke={brand.primary} strokeWidth="8" strokeLinecap="round" strokeDasharray="980" strokeDashoffset={980*(1-pr)}/>{groups.map((g,i)=>{const q=i/(groups.length-1);const x=90+q*700,y=530-q*400;const visible=pr>q*.88;return <g key={g.label} opacity={visible?1:.22}><circle cx={x} cy={y} r={i===0?22:16} fill={brand.surface} stroke={i===0?brand.accent:brand.primary} strokeWidth={i===0?8:4}/><text x={x+24} y={y+7} fontSize="17" fontWeight="800" fill={brand.ink}>{g.label}</text></g>})}</svg></Safe><Footer/><EndTransition id="PTR-DEPTH-PASS" duration={timings.territory}/></AbsoluteFill>}

function Journey(){const f=useCurrentFrame(),{fps}=useVideoConfig();const pr=interpolate(f,[.25*fps,11.2*fps],[0,1],clamp),active=Math.min(groups.length-1,Math.floor(pr*groups.length));const x=100+pr*760,y=780+Math.sin(pr*Math.PI*3.2)*210;return <AbsoluteFill style={{background:brand.surface,color:brand.ink}}><PremiumMaterial id="MAT-REFRACTION-POOL" brand={brand}/><Safe><div style={{paddingTop:45}}><Header label="JOURNEY"/><h2 style={{fontSize:76,lineHeight:.91,letterSpacing:-3.5,margin:'26px 0 0'}}>La ruta <span style={{color:brand.accent}}>avanza</span><br/>con la semana.</h2></div><div style={{position:'absolute',left:0,right:0,top:390,height:820}}><svg viewBox="0 0 900 820" style={{width:'100%',height:'100%'}}><path d="M70 650 C180 150 330 760 470 420 C610 120 720 630 840 220" fill="none" stroke={brand.line} strokeWidth="48" strokeLinecap="round" opacity=".55"/><path d="M70 650 C180 150 330 760 470 420 C610 120 720 630 840 220" fill="none" stroke={brand.surface} strokeWidth="4" strokeDasharray="14 18"/><path d="M70 650 C180 150 330 760 470 420 C610 120 720 630 840 220" fill="none" stroke={brand.primary} strokeWidth="10" strokeLinecap="round" strokeDasharray="1180" strokeDashoffset={1180*(1-pr)}/>{groups.map((g,i)=>{const q=(i+.5)/groups.length,xx=88+q*700,yy=650+Math.sin(q*Math.PI*3.2)*205,on=i===active;return <g key={g.label}><circle cx={xx} cy={yy} r={on?24:14} fill={brand.surface} stroke={on?brand.accent:brand.primary} strokeWidth={on?8:4}/>{on&&<circle cx={xx} cy={yy} r="6" fill={brand.accent}/>}</g>})}</svg><div style={{position:'absolute',left:x-20,top:y-20,width:40,height:40,background:brand.primary,rotate:'45deg',borderRadius:'52% 48% 55% 45% / 60% 42% 58% 40%',boxShadow:`0 0 0 12px ${brand.surface},0 18px 40px rgba(0,0,0,.16)`}}/></div><div style={{position:'absolute',left:20,right:20,bottom:120,padding:'26px 30px',borderRadius:28,background:`color-mix(in srgb, ${brand.surface} 88%, transparent)`,border:`1px solid ${brand.line}`,backdropFilter:'blur(14px)',display:'grid',gridTemplateColumns:'150px 1fr',gap:24,alignItems:'center'}}><div><div style={{fontSize:15,fontWeight:900,letterSpacing:2,color:brand.accent}}>TRAMO</div><strong style={{fontSize:56}}>{String(active+1).padStart(2,'0')}<small style={{fontSize:20,color:brand.muted}}> / 05</small></strong></div><div><div style={{fontSize:22,fontWeight:900,color:brand.accent}}>{groups[active].label}</div><div style={{fontSize:29,fontWeight:820,lineHeight:1.05,marginTop:9}}>{groups[active].items.slice(0,2).join(' · ')}</div></div></div></Safe><Footer/><EndTransition id="PTR-REFRACTION-PASS" duration={timings.journey}/></AbsoluteFill>}

function Nodes(){const f=useCurrentFrame(),{fps}=useVideoConfig();const active=Math.min(groups.length-1,Math.floor(interpolate(f,[.2*fps,8.4*fps],[0,groups.length],clamp))),g=groups[active];return <AbsoluteFill style={{background:brand.surface,color:brand.ink}}><PremiumMaterial id="MAT-MOSAIC-CELLS" brand={brand}/><Safe><div style={{paddingTop:45}}><Header label="DESTINOS"/><h2 style={{fontSize:76,lineHeight:.92,letterSpacing:-3.7,margin:'26px 0 0'}}>Cada nodo cuenta<br/><span style={{color:brand.accent}}>a dónde llegamos.</span></h2></div><div style={{position:'absolute',left:0,right:0,top:430,bottom:160,display:'grid',gridTemplateColumns:'210px 1fr',gap:20}}><div style={{display:'grid',gap:10,alignContent:'start'}}>{groups.map((x,i)=><div key={x.label} style={{padding:'16px 18px',background:i===active?brand.accent:brand.surface,border:`1px solid ${i===active?brand.accent:brand.line}`,color:i===active?brand.surface:brand.ink,fontSize:14,fontWeight:900,letterSpacing:1.4}}>{x.label}</div>)}</div><div style={{background:`color-mix(in srgb, ${brand.surface} 94%, transparent)`,border:`1px solid ${brand.line}`,borderRadius:30,padding:'32px 34px',boxShadow:'0 24px 65px rgba(0,0,0,.07)'}}><div style={{fontSize:18,fontWeight:900,letterSpacing:2.2,color:brand.accent}}>{g.label}</div><div style={{marginTop:32,display:'grid',gridTemplateColumns:'1fr 1fr',gap:'18px 22px'}}>{g.items.map((x,i)=><div key={x} style={{minHeight:100,padding:'18px 20px',borderTop:`4px solid ${i===0?brand.accent:brand.primary}`,background:brand.surfaceAlt,borderRadius:'0 0 18px 18px',fontSize:25,fontWeight:800,lineHeight:1.08}}>{x}</div>)}</div></div></div></Safe><Footer/><EndTransition id="PTR-EDITORIAL-RULE" duration={timings.nodes}/></AbsoluteFill>}

function Value(){const f=useCurrentFrame(),{fps}=useVideoConfig();const hero=interpolate(f,[.4*fps,1.7*fps],[.86,1],clamp),ring=interpolate(f,[1.6*fps,6.8*fps],[0,290],clamp);return <AbsoluteFill style={{background:brand.surface,color:brand.ink}}><PremiumMaterial id="MAT-DATA-ORBIT" brand={brand}/><Safe><div style={{paddingTop:55}}><Header label="VALOR / INFORMACIÓN"/></div><div style={{position:'absolute',left:0,top:320,width:520,transform:`scale(${hero})`,transformOrigin:'0 50%'}}><div style={{fontSize:24,fontWeight:900,letterSpacing:2.4,color:brand.accent}}>GARRAFÓN DE 20 LITROS</div><div style={{fontSize:190,lineHeight:.74,fontWeight:950,letterSpacing:-12,marginTop:34}}>$10</div><div style={{fontSize:35,fontWeight:800,marginTop:42}}>a domicilio</div><div style={{width:ring,height:6,background:brand.primary,borderRadius:99,marginTop:36}}/></div><div style={{position:'absolute',right:0,top:390,width:360,display:'grid',gap:16}}><div style={{padding:'28px 30px',border:`1px solid ${brand.line}`,borderRadius:24,background:brand.surfaceAlt}}><strong style={{fontSize:58}}>25</strong><div style={{fontSize:19,lineHeight:1.15,marginTop:12}}>purificadoras en funcionamiento</div></div><div style={{padding:'28px 30px',background:brand.accent,color:brand.surface,borderRadius:24}}><div style={{fontSize:16,fontWeight:900,letterSpacing:2}}>SANITARIO</div><div style={{fontSize:27,lineHeight:1.08,fontWeight:820,marginTop:14}}>Acompañamiento de COESPRIS</div></div></div></Safe><Footer/><EndTransition id="PTR-QUIET-FADE" duration={timings.value}/></AbsoluteFill>}

function Close(){const f=useCurrentFrame(),{fps}=useVideoConfig();const op=interpolate(f,[0,.8*fps],[0,1],clamp),w=interpolate(f,[.3*fps,4.5*fps],[16,80],clamp);return <AbsoluteFill style={{background:brand.surface,color:brand.ink}}><PremiumMaterial id="MAT-ASYMMETRIC-FRAME" brand={brand}/><Safe><div style={{paddingTop:180,textAlign:'center',opacity:op}}><div style={{fontSize:17,fontWeight:900,letterSpacing:3,color:brand.accent}}>RUTAS PROGRAMADAS</div><div style={{width:`${w}%`,maxWidth:620,height:4,background:brand.accent,margin:'32px auto 0'}}/><h2 style={{fontSize:82,lineHeight:.95,letterSpacing:-3.8,maxWidth:780,margin:'78px auto 0'}}>Consulta la ruta<br/>de tu <span style={{color:brand.accent}}>día.</span></h2><div style={{margin:'90px auto 0',width:650,padding:'28px 32px',borderTop:`1px solid ${brand.line}`,borderBottom:`1px solid ${brand.line}`}}><div style={{fontSize:16,fontWeight:900,letterSpacing:2.4,color:brand.muted}}>LÍNEA DE INFORMACIÓN</div><div style={{fontSize:61,fontWeight:900,letterSpacing:-2,marginTop:16}}>312 311 9041</div><div style={{fontSize:17,color:brand.muted,marginTop:10}}>Consultas e información · no es línea de pedidos</div></div><div style={{fontSize:19,fontWeight:800,marginTop:58}}>Agua Bienestar</div></div></Safe><Footer/></AbsoluteFill>}

export function AguaRoutePremium45QA(){return <AbsoluteFill style={{background:brand.surface}}><Sequence from={0} durationInFrames={timings.hook} premountFor={30}><Hook/></Sequence><Sequence from={timings.hook} durationInFrames={timings.territory} premountFor={30}><Territory/></Sequence><Sequence from={timings.hook+timings.territory} durationInFrames={timings.journey} premountFor={30}><Journey/></Sequence><Sequence from={timings.hook+timings.territory+timings.journey} durationInFrames={timings.nodes} premountFor={30}><Nodes/></Sequence><Sequence from={timings.hook+timings.territory+timings.journey+timings.nodes} durationInFrames={timings.value} premountFor={30}><Value/></Sequence><Sequence from={timings.hook+timings.territory+timings.journey+timings.nodes+timings.value} durationInFrames={timings.close} premountFor={30}><Close/></Sequence></AbsoluteFill>}
