import {useMemo,useState} from 'react'
import type {AssetRecord,CreativeBrief,Domain,MasterStoryboard,MasterVisualMap,OperationalMaster,Template,VisualArchitecture} from '../types'
import {buildProductionPlans,productionPrompt} from '../lib/productionPlanner'
import {directionsForMaster} from '../lib/visualDirector'
import {VisualDirectionCard} from './VisualDirectionCard'

export function BriefWorkbench({domains,masters,storyboards,templates,assets,visualMaps,visualArchitectures,onOpen}:{domains:Domain[];masters:OperationalMaster[];storyboards:MasterStoryboard[];templates:Template[];assets:AssetRecord[];visualMaps:MasterVisualMap[];visualArchitectures:VisualArchitecture[];onOpen:(t:Template)=>void}){
  const[topic,setTopic]=useState('')
  const[format,setFormat]=useState('')
  const[objective,setObjective]=useState('')
  const[materials,setMaterials]=useState('')
  const[copied,setCopied]=useState(false)
  const[selectedVisualId,setSelectedVisualId]=useState('')
  const brief:CreativeBrief=useMemo(()=>({topic,format:format||undefined,objective:objective||undefined,materials:materials.split(',').map(x=>x.trim()).filter(Boolean)}),[topic,format,objective,materials])
  const plans=useMemo(()=>topic.trim()?buildProductionPlans({brief,domains,masters,storyboards,templates,assets,limit:3}):[],[brief,domains,masters,storyboards,templates,assets,topic])
  const primary=plans[0]
  const directions=useMemo(()=>directionsForMaster(primary?.master,visualMaps,visualArchitectures,format||undefined),[primary,visualMaps,visualArchitectures,format])
  const selectedVisual=directions.find(x=>x.architecture.id===selectedVisualId)||directions[0]
  const copyPlan=async()=>{if(!primary)return;await navigator.clipboard?.writeText(productionPrompt(primary,selectedVisual));setCopied(true);setTimeout(()=>setCopied(false),1200)}
  return <section className="briefWorkbench"><div className="briefWorkbench__intro"><span className="kicker">PRODUCTION PLANNER v0.7</span><h2>Del brief a tres direcciones visuales.</h2><p>Detecta dominio, Master y storyboard; verifica assets y propone tres arquitecturas distintas antes de abrir un template.</p></div><div className="briefWorkbench__form"><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Tema: rehabilitación de pozo, rutas semanales, brigada…"/><div className="briefWorkbench__row"><select value={format} onChange={e=>setFormat(e.target.value)}><option value="">Formato automático</option><option value="reel">Reel</option><option value="carousel">Carrusel</option><option value="story">Story</option><option value="data">Datos</option><option value="presentation">Presentación</option></select><input value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Objetivo: explicar beneficio…"/></div><input value={materials} onChange={e=>setMaterials(e.target.value)} placeholder="Material: 6 fotos, inversión, beneficiarios…"/></div>{primary&&<div className="productionPlan"><div className="productionPlan__head"><div><small>MASTER RECOMENDADO</small><strong>{primary.master.id} · {primary.master.name}</strong></div><div className="readiness"><b>{primary.readiness}%</b><span>asset readiness</span></div><button onClick={copyPlan}>{copied?'Copiado':'Copiar prompt de producción'}</button></div><div className="productionPlan__visuals"><div className="productionPlan__sectionTitle"><small>3 DIRECCIONES VISUALES</small><span>elige arquitectura antes del template</span></div><div className="visualDirectionStrip">{directions.map(d=><VisualDirectionCard key={d.architecture.id} item={d} selected={selectedVisual?.architecture.id===d.architecture.id} onSelect={()=>setSelectedVisualId(d.architecture.id)}/>)}</div></div><div className="productionPlan__beats">{primary.storyboard.beats.map((b,i)=><div key={b.id}><b>{String(i+1).padStart(2,'0')}</b><span>{b.purpose}</span><small>{b.fields.join(' · ')}</small></div>)}</div>{primary.blockers.length>0&&<div className="productionPlan__blockers"><b>Antes de producción:</b>{primary.blockers.map(x=><span key={x}>{x}</span>)}</div>}<div className="productionPlan__templates">{primary.templates.slice(0,4).map(t=><button key={t.id} onClick={()=>onOpen(t)}><b>{t.id}</b><span>{t.name}</span></button>)}</div>{plans.length>1&&<div className="productionPlan__alts"><small>ALTERNATIVAS DE MASTER</small>{plans.slice(1).map(p=><span key={p.master.id}>{p.master.id} · {p.master.name} · {p.readiness}%</span>)}</div>}</div>}</section>
}
