import { motion, useReducedMotion } from 'motion/react'
import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { gsap } from 'gsap'

const EASE=[0.22,1,0.36,1] as const

export function KineticHeadline({lines,accentIndex=-1}:{lines:string[];accentIndex?:number}){const reduce=useReducedMotion();return <div>{lines.map((line,i)=><div key={i} style={{overflow:'hidden'}}><motion.div initial={reduce?false:{y:'105%',opacity:0}} animate={{y:0,opacity:1}} transition={{delay:i*.08,duration:.58,ease:EASE}} style={{fontWeight:900,color:i===accentIndex?'var(--ce-accent)':'inherit'}}>{line}</motion.div></div>)}</div>}

export function NumberReveal({value,duration=.9,suffix=''}:{value:number;duration?:number;suffix?:string}){const reduce=useReducedMotion();const [shown,setShown]=useState(reduce?value:0);useEffect(()=>{if(reduce){setShown(value);return}let raf=0;const start=performance.now();const loop=(now:number)=>{const p=Math.min(1,(now-start)/(duration*1000));const eased=1-Math.pow(1-p,3);setShown(Math.round(value*eased));if(p<1)raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[value,duration,reduce]);return <span>{shown.toLocaleString()}{suffix}</span>}

export function PersistentBand({children}:{children:ReactNode}){return <motion.div initial={{y:24,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.5,ease:EASE}} style={{position:'absolute',left:0,right:0,bottom:0,background:'white',borderTop:'4px solid var(--ce-accent)',padding:'14px 22px',zIndex:20}}>{children}</motion.div>}

export function ProgressiveList({items}:{items:string[]}){const reduce=useReducedMotion();return <div style={{display:'grid',gap:8}}>{items.map((x,i)=><motion.div key={x} initial={reduce?false:{opacity:0,x:-14}} animate={{opacity:1,x:0}} transition={{delay:i*.1,duration:.4,ease:EASE}} style={{display:'flex',gap:8,alignItems:'center'}}><b style={{fontSize:10,color:'var(--ce-accent)'}}>{String(i+1).padStart(2,'0')}</b><span>{x}</span></motion.div>)}</div>}

export function ConnectorCascade({count=3}:{count?:number}){return <div style={{display:'flex',alignItems:'center',width:'100%'}}>{Array.from({length:count}).map((_,i)=><span key={i} style={{display:'contents'}}><motion.i initial={{scale:0}} animate={{scale:1}} transition={{delay:i*.22}} style={{width:18,height:18,borderRadius:'50%',background:'var(--ce-primary)',display:'block'}}/>{i<count-1&&<motion.b initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:i*.22+.12,duration:.45,ease:EASE}} style={{height:2,background:'var(--ce-line)',flex:1,transformOrigin:'left'}}/>}</span>)}</div>}

export function PhotoStack(){return <div style={{position:'relative',height:220}}>{[0,1,2].map((i)=><motion.div key={i} initial={{opacity:0,y:18,rotate:(i-1)*4}} animate={{opacity:1,y:0,rotate:(i-1)*2}} transition={{delay:i*.12,duration:.5,ease:EASE}} style={{position:'absolute',inset:`${i*10}px ${28-i*10}px ${20-i*6}px ${i*22}px`,background:i===1?'var(--ce-secondary)':'var(--ce-primary)',border:'6px solid white'}}/>)}</div>}

export function GsapStreetJourney(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const vehicle=ref.current.querySelector('[data-vehicle]');const ctx=gsap.context(()=>{gsap.timeline({repeat:-1,repeatDelay:.7}).fromTo(vehicle,{x:0,y:45,scale:.86,opacity:0},{x:90,y:20,scale:.92,opacity:1,duration:.7,ease:'power2.out'}).to(vehicle,{x:230,y:0,scale:1,duration:1.4,ease:'power1.inOut'}).to(vehicle,{x:330,y:-28,scale:.94,duration:.8,ease:'power1.in'})},ref);return()=>ctx.revert()},[]);return <div ref={ref} style={{height:150,position:'relative',overflow:'hidden'}}><svg viewBox="0 0 420 150" style={{position:'absolute',inset:0,width:'100%',height:'100%'}}><path d="M0 118 C110 55 170 145 265 88 S365 55 430 18" fill="none" stroke="var(--ce-line)" strokeWidth="28" strokeLinecap="round"/><path d="M0 118 C110 55 170 145 265 88 S365 55 430 18" fill="none" stroke="white" strokeWidth="2" strokeDasharray="10 10"/></svg><div data-vehicle style={{position:'absolute',left:16,bottom:22,width:58,height:30,borderRadius:6,background:'var(--ce-primary)',boxShadow:'0 8px 18px #0002'}}><i style={{position:'absolute',width:12,height:12,borderRadius:'50%',background:'var(--ce-ink)',left:8,bottom:-5}}/><i style={{position:'absolute',width:12,height:12,borderRadius:'50%',background:'var(--ce-ink)',right:8,bottom:-5}}/></div></div>}
