import type {ReactNode} from 'react'
import {interpolate,useCurrentFrame,useVideoConfig} from 'remotion'
import {clamp,type VideoBrand} from '../compositions/shared'

export type PremiumMaterialId='MAT-LIQUID-GLASS'|'MAT-REFRACTION-POOL'|'MAT-CAUSTIC-LINES'|'MAT-PAPER-LAYER'|'MAT-CUTOUT-SHADOW'|'MAT-EDITORIAL-RULES'|'MAT-ASYMMETRIC-FRAME'|'MAT-CONTOUR-FIELD'|'MAT-TERRITORY-MESH'|'MAT-TECHNICAL-GRID'|'MAT-SCAN-WINDOW'|'MAT-DATA-STAGE'|'MAT-DATA-ORBIT'|'MAT-DOCUMENTARY-TAPE'|'MAT-CONTACT-SHEET'|'MAT-CINEMA-MATTE'|'MAT-DEPTH-FOG'|'MAT-MOSAIC-CELLS'

export const executablePremiumMaterialIds:PremiumMaterialId[]=['MAT-LIQUID-GLASS','MAT-REFRACTION-POOL','MAT-CAUSTIC-LINES','MAT-PAPER-LAYER','MAT-CUTOUT-SHADOW','MAT-EDITORIAL-RULES','MAT-ASYMMETRIC-FRAME','MAT-CONTOUR-FIELD','MAT-TERRITORY-MESH','MAT-TECHNICAL-GRID','MAT-SCAN-WINDOW','MAT-DATA-STAGE','MAT-DATA-ORBIT','MAT-DOCUMENTARY-TAPE','MAT-CONTACT-SHEET','MAT-CINEMA-MATTE','MAT-DEPTH-FOG','MAT-MOSAIC-CELLS']

const role=(brand:VideoBrand,key:'surface'|'surfaceAlt'|'primary'|'secondary'|'accent'|'ink'|'line')=>key==='surfaceAlt'?(brand.surfaceAlt??brand.surface):brand[key]
const pct=(n:number)=>`${n}%`

export function PremiumMaterial({id,brand,children}:{id:PremiumMaterialId;brand:VideoBrand;children?:ReactNode}){
  const frame=useCurrentFrame();const{fps}=useVideoConfig();const t=interpolate(frame,[0,6*fps],[0,1],clamp);const drift=interpolate(t,[0,1],[-4,6],clamp)
  const base={position:'absolute' as const,inset:0,overflow:'hidden' as const,background:brand.surface}
  const content=<div style={{position:'relative',zIndex:5,width:'100%',height:'100%'}}>{children}</div>
  if(id==='MAT-LIQUID-GLASS')return <div style={base}><div style={{position:'absolute',width:'72%',height:'72%',right:'-18%',top:'-14%',borderRadius:'44% 56% 62% 38% / 56% 42% 58% 44%',background:`color-mix(in srgb, ${brand.secondary} 58%, transparent)`,transform:`translate(${drift}%,${-drift*.6}%) rotate(${drift}deg)`}}/><div style={{position:'absolute',width:'44%',height:'44%',right:'5%',top:'12%',border:`1px solid ${brand.primary}`,borderRadius:'50%',background:`color-mix(in srgb, ${brand.surface} 66%, transparent)`,backdropFilter:'blur(8px)'}}/>{content}</div>
  if(id==='MAT-REFRACTION-POOL')return <div style={base}>{[0,1,2].map(i=><div key={i} style={{position:'absolute',width:`${38+i*12}%`,height:`${38+i*12}%`,left:`${8+i*20}%`,top:`${14+i*9}%`,borderRadius:'50%',border:`${i?1:2}px solid ${i===0?brand.accent:brand.line}`,background:i===1?`color-mix(in srgb, ${brand.secondary} 38%, transparent)`:'transparent',transform:`translate(${drift*(i+1)*.35}%,${-drift*(i+1)*.25}%)`}}/>)}{content}</div>
  if(id==='MAT-CAUSTIC-LINES')return <div style={base}>{Array.from({length:9}).map((_,i)=><div key={i} style={{position:'absolute',left:`${-15+i*15}%`,top:`${12+(i%3)*24}%`,width:'45%',height:3,borderRadius:999,background:i%4===0?brand.primary:brand.line,opacity:i%4===0?.42:.35,transform:`translateX(${drift*(i%2?1:-1)}%) rotate(${i%2?8:-9}deg)`}}/>)}{content}</div>
  if(id==='MAT-PAPER-LAYER')return <div style={{...base,background:role(brand,'surfaceAlt')}}><div style={{position:'absolute',inset:'7% 10% 12% 7%',background:brand.surface,boxShadow:'10px 14px 0 rgba(0,0,0,.05)',transform:'rotate(-1.2deg)'}}/><div style={{position:'absolute',right:'6%',top:'9%',width:'28%',height:'22%',background:`color-mix(in srgb, ${brand.secondary} 56%, ${brand.surface})`,transform:'rotate(3deg)',boxShadow:'0 9px 26px rgba(0,0,0,.08)'}}/><div style={{position:'absolute',left:'4%',bottom:'15%',width:'20%',height:10,background:brand.accent}}/>{content}</div>
  if(id==='MAT-CUTOUT-SHADOW')return <div style={base}><div style={{position:'absolute',left:'8%',top:'12%',width:'68%',height:'68%',borderRadius:'38px 8px 38px 8px',background:brand.surfaceAlt??brand.secondary,boxShadow:`30px 30px 0 color-mix(in srgb, ${brand.ink} 9%, transparent)`}}/><div style={{position:'absolute',right:'10%',bottom:'8%',width:'34%',height:'34%',borderRadius:'50%',background:`color-mix(in srgb, ${brand.secondary} 70%, ${brand.surface})`,boxShadow:'-18px 14px 0 rgba(0,0,0,.05)'}}/>{content}</div>
  if(id==='MAT-EDITORIAL-RULES')return <div style={base}>{Array.from({length:8}).map((_,i)=><div key={i} style={{position:'absolute',left:0,right:0,top:pct((i+1)*11),height:1,background:brand.line,opacity:i%2?.34:.56}}/>)}<div style={{position:'absolute',left:'8%',top:0,bottom:0,width:6,background:brand.accent}}/>{content}</div>
  if(id==='MAT-ASYMMETRIC-FRAME')return <div style={base}><div style={{position:'absolute',left:'4%',top:'6%',right:'13%',bottom:'15%',border:`2px solid ${brand.line}`,borderRadius:'42px 8px 8px 8px'}}/><div style={{position:'absolute',right:'5%',top:'15%',width:'16%',height:'32%',background:brand.accent}}/><div style={{position:'absolute',left:'14%',bottom:'7%',width:'46%',height:7,background:brand.ink}}/>{content}</div>
  if(id==='MAT-CONTOUR-FIELD')return <div style={base}>{[0,1,2,3,4].map(i=><div key={i} style={{position:'absolute',width:`${34+i*13}%`,height:`${25+i*11}%`,left:`${15-i*3}%`,top:`${20+i*3}%`,borderRadius:`${42+i*3}% ${58-i*3}% 48% 52% / 58% 44% 56% 42%`,border:`1px solid ${i===0?brand.primary:brand.line}`,opacity:.35+i*.08,transform:`rotate(${i*4-8+drift*.15}deg)`}}/>)}{content}</div>
  if(id==='MAT-TERRITORY-MESH')return <div style={{...base,background:role(brand,'surfaceAlt')}}>{Array.from({length:9}).map((_,i)=><div key={`v${i}`} style={{position:'absolute',top:0,bottom:0,left:pct((i+1)*10),width:1,background:brand.line,opacity:.38}}/>)}{Array.from({length:12}).map((_,i)=><div key={`h${i}`} style={{position:'absolute',left:0,right:0,top:pct((i+1)*7.5),height:1,background:brand.line,opacity:.25}}/>)}<div style={{position:'absolute',left:'58%',top:'22%',width:90,height:90,borderRadius:'50%',border:`2px solid ${brand.accent}`,boxShadow:`0 0 0 24px color-mix(in srgb, ${brand.accent} 7%, transparent)`}}/>{content}</div>
  if(id==='MAT-TECHNICAL-GRID')return <div style={base}><div style={{position:'absolute',inset:0,background:`repeating-linear-gradient(0deg,transparent 0 39px,${brand.line} 39px 40px),repeating-linear-gradient(90deg,transparent 0 49px,${brand.line} 49px 50px)`,opacity:.34}}/><div style={{position:'absolute',left:'8%',top:'8%',width:120,height:6,background:brand.primary}}/>{content}</div>
  if(id==='MAT-SCAN-WINDOW')return <div style={base}><div style={{position:'absolute',inset:'9% 7%',border:`1px solid ${brand.line}`}}/><div style={{position:'absolute',left:pct(10+t*78),top:'9%',bottom:'9%',width:3,background:brand.accent,boxShadow:`0 0 22px ${brand.accent}`}}/><div style={{position:'absolute',left:'7%',right:'7%',top:'50%',height:1,background:brand.line}}/>{content}</div>
  if(id==='MAT-DATA-STAGE')return <div style={{...base,background:role(brand,'surfaceAlt')}}><div style={{position:'absolute',left:'8%',top:'11%',width:'62%',height:'65%',background:brand.surface,border:`1px solid ${brand.line}`,borderRadius:28}}/><div style={{position:'absolute',right:'8%',bottom:'9%',width:'28%',height:'43%',background:brand.accent,borderRadius:'8px 28px 8px 8px'}}/>{content}</div>
  if(id==='MAT-DATA-ORBIT')return <div style={base}>{[0,1,2].map(i=><div key={i} style={{position:'absolute',left:'50%',top:'48%',translate:'-50% -50%',width:180+i*110,height:180+i*110,borderRadius:'50%',border:`${i===0?3:1}px solid ${i===0?brand.accent:brand.line}`,transform:`rotate(${drift*(i+1)}deg)`}}/>)}<div style={{position:'absolute',left:'50%',top:'48%',width:18,height:18,translate:'-50% -50%',borderRadius:'50%',background:brand.primary}}/>{content}</div>
  if(id==='MAT-DOCUMENTARY-TAPE')return <div style={base}><div style={{position:'absolute',left:'7%',top:'8%',width:'42%',height:28,background:`color-mix(in srgb, ${brand.secondary} 76%, ${brand.surface})`,transform:'rotate(-2deg)',opacity:.8}}/><div style={{position:'absolute',right:'6%',bottom:'9%',width:'46%',height:36,background:brand.ink,opacity:.92}}/><div style={{position:'absolute',left:'4%',bottom:'7%',width:8,height:'42%',background:brand.accent}}/>{content}</div>
  if(id==='MAT-CONTACT-SHEET')return <div style={base}><div style={{position:'absolute',inset:'7%',display:'grid',gridTemplateColumns:'1.35fr .75fr 1fr',gridTemplateRows:'1fr .7fr',gap:9}}>{Array.from({length:6}).map((_,i)=><div key={i} style={{background:i===0?role(brand,'surfaceAlt'):brand.surface,border:`1px solid ${brand.line}`,gridRow:i===0?'span 2':undefined}}/> )}</div>{content}</div>
  if(id==='MAT-CINEMA-MATTE')return <div style={{...base,background:brand.ink}}><div style={{position:'absolute',left:'8%',top:'9%',right:'8%',bottom:'9%',background:`linear-gradient(135deg,color-mix(in srgb, ${brand.accent} 28%, ${brand.ink}),${brand.ink} 62%)`,borderRadius:30}}/><div style={{position:'absolute',left:'13%',right:'13%',top:'48%',height:1,background:brand.line,opacity:.4}}/>{content}</div>
  if(id==='MAT-DEPTH-FOG')return <div style={base}>{[0,1,2].map(i=><div key={i} style={{position:'absolute',left:`${-18+i*36}%`,top:`${18+i*14}%`,width:'52%',height:'46%',borderRadius:'50%',background:i===1?brand.secondary:role(brand,'surfaceAlt'),filter:'blur(34px)',opacity:.38,transform:`translateX(${drift*(i%2?1:-1)}%)`}}/>)}{content}</div>
  return <div style={base}><div style={{position:'absolute',inset:'7%',display:'grid',gridTemplateColumns:'1.45fr .75fr 1fr',gridTemplateRows:'1.15fr .85fr',gap:10}}>{Array.from({length:6}).map((_,i)=><div key={i} style={{background:i===1?brand.accent:i===4?role(brand,'surfaceAlt'):brand.surface,border:`1px solid ${brand.line}`,gridRow:i===0?'span 2':undefined,borderRadius:i===0?'30px 8px 8px 30px':8}}/>)}</div>{content}</div>
}
